//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flerp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flerp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Category_Email {
            get {
                return ResourceManager.GetString("Category_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Category_Null {
            get {
                return ResourceManager.GetString("Category_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Delim_Hyphen {
            get {
                return ResourceManager.GetString("Delim_Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A{0}: {1}.
        /// </summary>
        internal static string Email_ExtractAttachments_Label {
            get {
                return ResourceManager.GetString("Email_ExtractAttachments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .eml.
        /// </summary>
        internal static string FileExtension_Email {
            get {
                return ResourceManager.GetString("FileExtension_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .flerp.
        /// </summary>
        internal static string FileExtension_Flerp {
            get {
                return ResourceManager.GetString("FileExtension_Flerp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zip.
        /// </summary>
        internal static string FileExtension_Zip {
            get {
                return ResourceManager.GetString("FileExtension_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string FlerpId_BinderPad {
            get {
                return ResourceManager.GetString("FlerpId_BinderPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        internal static string FlerpId_DocPad {
            get {
                return ResourceManager.GetString("FlerpId_DocPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string FlerpId_RevPad {
            get {
                return ResourceManager.GetString("FlerpId_RevPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stubs cannot be deleted..
        /// </summary>
        internal static string Msg_StubsCannotBeDeleted {
            get {
                return ResourceManager.GetString("Msg_StubsCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document from unauditable source..
        /// </summary>
        internal static string Name_Unauditable {
            get {
                return ResourceManager.GetString("Name_Unauditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Stub_ClosedNullComment {
            get {
                return ResourceManager.GetString("Stub_ClosedNullComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Basket.
        /// </summary>
        internal static string UiCaption_ClearBasket {
            get {
                return ResourceManager.GetString("UiCaption_ClearBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete relation....
        /// </summary>
        internal static string UiLabel_DeleteRelation {
            get {
                return ResourceManager.GetString("UiLabel_DeleteRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok to proceed?.
        /// </summary>
        internal static string UiMsg_OkToProceed {
            get {
                return ResourceManager.GetString("UiMsg_OkToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Wildcard_Any {
            get {
                return ResourceManager.GetString("Wildcard_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string Wildcard_AnyFilenameDotAnyExtension {
            get {
                return ResourceManager.GetString("Wildcard_AnyFilenameDotAnyExtension", resourceCulture);
            }
        }
    }
}
