//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flerp.Data.EmailCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flerp.Data.EmailCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api-ssl.bitly.com/v3/link/clicks?access_token={0}&amp;link={1}.
        /// </summary>
        internal static string Bitly_PathClicks {
            get {
                return ResourceManager.GetString("Bitly_PathClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api-ssl.bitly.com/v3/shorten?access_token={0}&amp;longUrl={1}.
        /// </summary>
        internal static string Bitly_PathShorten {
            get {
                return ResourceManager.GetString("Bitly_PathShorten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a6110d4d6b489f2f12842fd9986caf4556633da2.
        /// </summary>
        internal static string Bitly_Users_AccessToken {
            get {
                return ResourceManager.GetString("Bitly_Users_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string BitlyApi_Label_Data {
            get {
                return ResourceManager.GetString("BitlyApi_Label_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link_clicks.
        /// </summary>
        internal static string BitlyApi_Label_LinkClicks {
            get {
                return ResourceManager.GetString("BitlyApi_Label_LinkClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string BitlyApi_Label_Url {
            get {
                return ResourceManager.GetString("BitlyApi_Label_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string BitlyApi_StatExtension {
            get {
                return ResourceManager.GetString("BitlyApi_StatExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.dropbox.com/1/metadata/auto/.
        /// </summary>
        internal static string Dropbox_PathMeta {
            get {
                return ResourceManager.GetString("Dropbox_PathMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.dropbox.com/1/shares/auto/.
        /// </summary>
        internal static string Dropbox_PathShare {
            get {
                return ResourceManager.GetString("Dropbox_PathShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;short_url=true.
        /// </summary>
        internal static string Dropbox_ShortUrlSwitch {
            get {
                return ResourceManager.GetString("Dropbox_ShortUrlSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded on {0}.
        /// </summary>
        internal static string Dropbox_Uploaded_on_0 {
            get {
                return ResourceManager.GetString("Dropbox_Uploaded_on_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VE8cm9jeDtEAAAAAAAB1t-aZdSe-d2chUc57bX-vXNeFZMad2sSej8MpOrgSC0JF.
        /// </summary>
        internal static string Dropbox_Users_AccessToken {
            get {
                return ResourceManager.GetString("Dropbox_Users_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\FrugalTPH\Dropbox\Apps\FLERP.
        /// </summary>
        internal static string Dropbox_Users_LocalCache {
            get {
                return ResourceManager.GetString("Dropbox_Users_LocalCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer .
        /// </summary>
        internal static string DropBoxApi_Bearer {
            get {
                return ResourceManager.GetString("DropBoxApi_Bearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        internal static string DropBoxApi_Label_Modified {
            get {
                return ResourceManager.GetString("DropBoxApi_Label_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string DropBoxApi_Label_Url {
            get {
                return ResourceManager.GetString("DropBoxApi_Label_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string DropBoxApi_TextPlain {
            get {
                return ResourceManager.GetString("DropBoxApi_TextPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .eml.
        /// </summary>
        internal static string Email_FileType {
            get {
                return ResourceManager.GetString("Email_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLERP.
        /// </summary>
        internal static string Email_FlerpName {
            get {
                return ResourceManager.GetString("Email_FlerpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOAUTH2.
        /// </summary>
        internal static string Email_XOAUTH2 {
            get {
                return ResourceManager.GetString("Email_XOAUTH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering autofac for Flerp.Data.Email.
        /// </summary>
        internal static string Registering_autofac_for_FlerpDataEmail {
            get {
                return ResourceManager.GetString("Registering_autofac_for_FlerpDataEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string String_Truncated {
            get {
                return ResourceManager.GetString("String_Truncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already present in the WebStore..
        /// </summary>
        internal static string uiMsg_Dropbox_FileAlreadyExists {
            get {
                return ResourceManager.GetString("uiMsg_Dropbox_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was copied to dropbox (via the local cache)..
        /// </summary>
        internal static string uiMsg_Dropbox_FileCopiedToDropbox {
            get {
                return ResourceManager.GetString("uiMsg_Dropbox_FileCopiedToDropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted from dropbox (via the local cache)..
        /// </summary>
        internal static string uiMsg_Dropbox_FileDeleted {
            get {
                return ResourceManager.GetString("uiMsg_Dropbox_FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string uiMsg_Email_ConnectedTo {
            get {
                return ResourceManager.GetString("uiMsg_Email_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from {0}.
        /// </summary>
        internal static string uiMsg_Email_DisconnectedFrom {
            get {
                return ResourceManager.GetString("uiMsg_Email_DisconnectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... \&quot;{0}\&quot;.
        /// </summary>
        internal static string uiMsg_Email_Downloading {
            get {
                return ResourceManager.GetString("uiMsg_Email_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no new Emails to retrieve..
        /// </summary>
        internal static string uiMsg_Email_NoneRetrieved {
            get {
                return ResourceManager.GetString("uiMsg_Email_NoneRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject.
        /// </summary>
        internal static string uiMsg_Email_NoSubject {
            get {
                return ResourceManager.GetString("uiMsg_Email_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new Emails were retrieved..
        /// </summary>
        internal static string uiMsg_Email_Retrieved {
            get {
                return ResourceManager.GetString("uiMsg_Email_Retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Wildcard_Any {
            get {
                return ResourceManager.GetString("Wildcard_Any", resourceCulture);
            }
        }
    }
}
